# Sort NumPy Arrays By Columns or Rows

In [1]:
import numpy as np

In [2]:
a = np.random.randint(100, size=(6, 4))
print(a)

[[46 28 73 54]
 [65 84 24 72]
 [14 90 78  0]
 [31 94 85  5]
 [18 91 84 62]
 [91 76 15 25]]


In [3]:
b = a[:, 0].argsort()
print(b)

[2 4 3 0 1 5]


In [5]:
c = a[a[:, 0].argsort()]
print(c)

[[14 90 78  0]
 [18 91 84 62]
 [31 94 85  5]
 [46 28 73 54]
 [65 84 24 72]
 [91 76 15 25]]


# Seach particular value
`np.where()`, `np.nonzero()`

In [6]:
# test np.where()

array_test = np.linspace(12, -12, 601)

index0 = np.where(array_test == 12)
index1 = np.where(array_test == 0)
index2 = np.where(array_test == -12)
print(index0, index1, index2)
print(array_test[index0])

(array([0]),) (array([300]),) (array([600]),)
[12.]
