# Sort NumPy Arrays By Columns or Rows

In [1]:
import numpy as np

In [2]:
a = np.random.randint(100, size=(6, 4))
print(a)

[[12 66 88 71]
 [41 89  7 36]
 [90 74 47 79]
 [84  8 99 52]
 [75 19 29 57]
 [41 92 16 92]]


In [3]:
b = a[:, 0].argsort()
print(b)

[0 1 5 4 3 2]


In [4]:
c = a[a[:, 0].argsort()]
print(c)

[[12 66 88 71]
 [41 89  7 36]
 [41 92 16 92]
 [75 19 29 57]
 [84  8 99 52]
 [90 74 47 79]]


# Seach particular value
`np.where()`, `np.nonzero()`

In [5]:
# test np.where()

array_test = np.linspace(12, -12, 601)

index0 = np.where(array_test == 12)
index1 = np.where(array_test == 0)
index2 = np.where(array_test == -12)
print(index0, index1, index2)
print(array_test[index0])

(array([0], dtype=int64),) (array([300], dtype=int64),) (array([600], dtype=int64),)
[12.]
